/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef DODGEBALL_PRIVATE_H
#define DODGEBALL_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.1.0.28"
#define VER_MAJOR	0
#define VER_MINOR	1
#define VER_RELEASE	0
#define VER_BUILD	28
#define COMPANY_NAME	""
#define FILE_VERSION	""
#define FILE_DESCRIPTION	"Dodgeball by Dean Rather"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"Dodgeball"
#define PRODUCT_VERSION	"Alpha"

#endif /*DODGEBALL_PRIVATE_H*/
